cdns3-starfive: Include dm/lists.h for device_bind_driver_to_node definition
GCC-14 will treat implicit function declarations as errors. Therefore
include the required header to fix

error: implicit declaration of function 'device_bind_driver_to_node' [-Wimplicit-function-declaration]

Signed-off-by: Khem Raj <raj.khem@gmail.com>